manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: petejohanson
      revision: shields/splitkb-aurora-corne-col-offset-fix
      import: app/west.yml
  self:
    path: config
