name: Build ZMK firmware

on:
  push:
    paths-ignore:
      - 'images/**'
      - 'keymap-drawer.config.yaml'
      - 'keymap/**'
      - '.vscode/**'
      - 'README.md'
      - '.gitattributes'

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
